# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(677, 609)
        MainWindow.setMaximumSize(QtCore.QSize(677, 613))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color:rgb(238, 238, 238);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.people_option = QtWidgets.QRadioButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.people_option.setFont(font)
        self.people_option.setChecked(True)
        self.people_option.setObjectName("people_option")
        self.gridLayout_2.addWidget(self.people_option, 2, 0, 1, 2)
        self.lineEdit_delay = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_delay.sizePolicy().hasHeightForWidth())
        self.lineEdit_delay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_delay.setFont(font)
        self.lineEdit_delay.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_delay.setMaxLength(2)
        self.lineEdit_delay.setFrame(False)
        self.lineEdit_delay.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_delay.setClearButtonEnabled(True)
        self.lineEdit_delay.setObjectName("lineEdit_delay")
        self.gridLayout_2.addWidget(self.lineEdit_delay, 8, 1, 1, 1)
        self.pause_btn = QtWidgets.QPushButton(self.tab)
        self.pause_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.pause_btn.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pause_btn.setFont(font)
        self.pause_btn.setStyleSheet("QPushButton {\n"
"    color: #000000;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ffff00, stop: 1 #fed348\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pause_btn.setObjectName("pause_btn")
        self.gridLayout_2.addWidget(self.pause_btn, 8, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 11, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 7, 0, 1, 1)
        self.lineEdit_page_number = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_page_number.sizePolicy().hasHeightForWidth())
        self.lineEdit_page_number.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_page_number.setFont(font)
        self.lineEdit_page_number.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_page_number.setMaxLength(3)
        self.lineEdit_page_number.setFrame(False)
        self.lineEdit_page_number.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_page_number.setClearButtonEnabled(True)
        self.lineEdit_page_number.setObjectName("lineEdit_page_number")
        self.gridLayout_2.addWidget(self.lineEdit_page_number, 9, 1, 1, 1)
        self.lineEdit_filename = QtWidgets.QLineEdit(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_filename.sizePolicy().hasHeightForWidth())
        self.lineEdit_filename.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_filename.setFont(font)
        self.lineEdit_filename.setAutoFillBackground(False)
        self.lineEdit_filename.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_filename.setMaxLength(500)
        self.lineEdit_filename.setFrame(False)
        self.lineEdit_filename.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_filename.setClearButtonEnabled(True)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.gridLayout_2.addWidget(self.lineEdit_filename, 11, 1, 1, 2)
        self.spinBox_try_count = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_try_count.sizePolicy().hasHeightForWidth())
        self.spinBox_try_count.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.spinBox_try_count.setFont(font)
        self.spinBox_try_count.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_try_count.setFrame(False)
        self.spinBox_try_count.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_try_count.setMinimum(2)
        self.spinBox_try_count.setMaximum(50)
        self.spinBox_try_count.setObjectName("spinBox_try_count")
        self.gridLayout_2.addWidget(self.spinBox_try_count, 7, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 9, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 8, 0, 1, 1)
        self.label_status = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.gridLayout_2.addWidget(self.label_status, 10, 0, 1, 3)
        self.pushButton_export = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_export.sizePolicy().hasHeightForWidth())
        self.pushButton_export.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_export.setFont(font)
        self.pushButton_export.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_export.setFlat(False)
        self.pushButton_export.setObjectName("pushButton_export")
        self.gridLayout_2.addWidget(self.pushButton_export, 12, 1, 1, 1)
        self.pushButton_close = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout_2.addWidget(self.pushButton_close, 9, 2, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout_2.addWidget(self.pushButton_start, 7, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.spinBox_speed = QtWidgets.QSpinBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_speed.sizePolicy().hasHeightForWidth())
        self.spinBox_speed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.spinBox_speed.setFont(font)
        self.spinBox_speed.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_speed.setWrapping(False)
        self.spinBox_speed.setFrame(False)
        self.spinBox_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_speed.setMinimum(-150)
        self.spinBox_speed.setMaximum(6000)
        self.spinBox_speed.setSingleStep(25)
        self.spinBox_speed.setObjectName("spinBox_speed")
        self.gridLayout_2.addWidget(self.spinBox_speed, 6, 1, 1, 1)
        self.company_option = QtWidgets.QRadioButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.company_option.setFont(font)
        self.company_option.setObjectName("company_option")
        self.gridLayout_2.addWidget(self.company_option, 3, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.label_26 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 1, 0, 1, 2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_start_2 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start_2.sizePolicy().hasHeightForWidth())
        self.pushButton_start_2.setSizePolicy(sizePolicy)
        self.pushButton_start_2.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_start_2.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_start_2.setFont(font)
        self.pushButton_start_2.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_start_2.setObjectName("pushButton_start_2")
        self.gridLayout_3.addWidget(self.pushButton_start_2, 3, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 5, QtCore.Qt.AlignHCenter)
        self.filename = QtWidgets.QLineEdit(self.tab_2)
        self.filename.setMinimumSize(QtCore.QSize(480, 38))
        self.filename.setMaximumSize(QtCore.QSize(480, 30))
        self.filename.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filename.setFrame(False)
        self.filename.setObjectName("filename")
        self.gridLayout_3.addWidget(self.filename, 2, 0, 1, 5)
        self.browse = QtWidgets.QPushButton(self.tab_2)
        self.browse.setMinimumSize(QtCore.QSize(180, 30))
        self.browse.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.browse.setFont(font)
        self.browse.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.browse.setObjectName("browse")
        self.gridLayout_3.addWidget(self.browse, 1, 0, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_status_2 = QtWidgets.QLabel(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status_2.sizePolicy().hasHeightForWidth())
        self.label_status_2.setSizePolicy(sizePolicy)
        self.label_status_2.setMinimumSize(QtCore.QSize(400, 60))
        self.label_status_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_status_2.setFont(font)
        self.label_status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_2.setObjectName("label_status_2")
        self.gridLayout_3.addWidget(self.label_status_2, 7, 0, 1, 5)
        self.pushButton_export_2 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_export_2.sizePolicy().hasHeightForWidth())
        self.pushButton_export_2.setSizePolicy(sizePolicy)
        self.pushButton_export_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_export_2.setFont(font)
        self.pushButton_export_2.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_export_2.setFlat(False)
        self.pushButton_export_2.setObjectName("pushButton_export_2")
        self.gridLayout_3.addWidget(self.pushButton_export_2, 8, 3, 1, 2)
        self.lineEdit_filename_2 = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_filename_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_filename_2.setSizePolicy(sizePolicy)
        self.lineEdit_filename_2.setMaximumSize(QtCore.QSize(350, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_filename_2.setFont(font)
        self.lineEdit_filename_2.setAutoFillBackground(False)
        self.lineEdit_filename_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_filename_2.setMaxLength(500)
        self.lineEdit_filename_2.setFrame(False)
        self.lineEdit_filename_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_filename_2.setClearButtonEnabled(True)
        self.lineEdit_filename_2.setObjectName("lineEdit_filename_2")
        self.gridLayout_3.addWidget(self.lineEdit_filename_2, 8, 1, 1, 2)
        self.lineEdit_delay_2 = QtWidgets.QLineEdit(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_delay_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_delay_2.setSizePolicy(sizePolicy)
        self.lineEdit_delay_2.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_delay_2.setFont(font)
        self.lineEdit_delay_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_delay_2.setMaxLength(2)
        self.lineEdit_delay_2.setFrame(False)
        self.lineEdit_delay_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_delay_2.setClearButtonEnabled(True)
        self.lineEdit_delay_2.setObjectName("lineEdit_delay_2")
        self.gridLayout_3.addWidget(self.lineEdit_delay_2, 6, 1, 1, 1)
        self.pushButton_close_2 = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close_2.sizePolicy().hasHeightForWidth())
        self.pushButton_close_2.setSizePolicy(sizePolicy)
        self.pushButton_close_2.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_close_2.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_close_2.setFont(font)
        self.pushButton_close_2.setStyleSheet("QPushButton {\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_close_2.setObjectName("pushButton_close_2")
        self.gridLayout_3.addWidget(self.pushButton_close_2, 3, 4, 1, 1)
        self.pause_btn_2 = QtWidgets.QPushButton(self.tab_2)
        self.pause_btn_2.setMinimumSize(QtCore.QSize(120, 0))
        self.pause_btn_2.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pause_btn_2.setFont(font)
        self.pause_btn_2.setStyleSheet("QPushButton {\n"
"    color: #000000;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ffff00, stop: 1 #fed348\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pause_btn_2.setObjectName("pause_btn_2")
        self.gridLayout_3.addWidget(self.pause_btn_2, 3, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_status_3 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status_3.sizePolicy().hasHeightForWidth())
        self.label_status_3.setSizePolicy(sizePolicy)
        self.label_status_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_status_3.setFont(font)
        self.label_status_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_3.setObjectName("label_status_3")
        self.gridLayout_4.addWidget(self.label_status_3, 8, 0, 1, 4)
        self.lineEdit_filename_3 = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_filename_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_filename_3.setSizePolicy(sizePolicy)
        self.lineEdit_filename_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_filename_3.setFont(font)
        self.lineEdit_filename_3.setAutoFillBackground(False)
        self.lineEdit_filename_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_filename_3.setMaxLength(500)
        self.lineEdit_filename_3.setFrame(False)
        self.lineEdit_filename_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_filename_3.setClearButtonEnabled(True)
        self.lineEdit_filename_3.setObjectName("lineEdit_filename_3")
        self.gridLayout_4.addWidget(self.lineEdit_filename_3, 9, 1, 1, 3)
        self.pushButton_export_3 = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_export_3.sizePolicy().hasHeightForWidth())
        self.pushButton_export_3.setSizePolicy(sizePolicy)
        self.pushButton_export_3.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_export_3.setFont(font)
        self.pushButton_export_3.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_export_3.setFlat(False)
        self.pushButton_export_3.setObjectName("pushButton_export_3")
        self.gridLayout_4.addWidget(self.pushButton_export_3, 10, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 4, QtCore.Qt.AlignHCenter)
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.lineEdit_delay_3 = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_delay_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_delay_3.setSizePolicy(sizePolicy)
        self.lineEdit_delay_3.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_delay_3.setFont(font)
        self.lineEdit_delay_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_delay_3.setMaxLength(2)
        self.lineEdit_delay_3.setFrame(False)
        self.lineEdit_delay_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_delay_3.setClearButtonEnabled(True)
        self.lineEdit_delay_3.setObjectName("lineEdit_delay_3")
        self.gridLayout_4.addWidget(self.lineEdit_delay_3, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 3, 0, 1, 1)
        self.lineEdit_page_number_2 = QtWidgets.QLineEdit(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_page_number_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_page_number_2.setSizePolicy(sizePolicy)
        self.lineEdit_page_number_2.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_page_number_2.setFont(font)
        self.lineEdit_page_number_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_page_number_2.setMaxLength(3)
        self.lineEdit_page_number_2.setFrame(False)
        self.lineEdit_page_number_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_page_number_2.setClearButtonEnabled(True)
        self.lineEdit_page_number_2.setObjectName("lineEdit_page_number_2")
        self.gridLayout_4.addWidget(self.lineEdit_page_number_2, 3, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 9, 0, 1, 1)
        self.pause_btn_3 = QtWidgets.QPushButton(self.tab_3)
        self.pause_btn_3.setMinimumSize(QtCore.QSize(120, 0))
        self.pause_btn_3.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pause_btn_3.setFont(font)
        self.pause_btn_3.setStyleSheet("QPushButton {\n"
"    color: #000000;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ffff00, stop: 1 #fed348\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pause_btn_3.setObjectName("pause_btn_3")
        self.gridLayout_4.addWidget(self.pause_btn_3, 3, 2, 1, 1)
        self.pushButton_start_3 = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start_3.sizePolicy().hasHeightForWidth())
        self.pushButton_start_3.setSizePolicy(sizePolicy)
        self.pushButton_start_3.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start_3.setFont(font)
        self.pushButton_start_3.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_start_3.setObjectName("pushButton_start_3")
        self.gridLayout_4.addWidget(self.pushButton_start_3, 1, 2, 1, 1)
        self.pushButton_close_3 = QtWidgets.QPushButton(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close_3.sizePolicy().hasHeightForWidth())
        self.pushButton_close_3.setSizePolicy(sizePolicy)
        self.pushButton_close_3.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_close_3.setFont(font)
        self.pushButton_close_3.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_close_3.setObjectName("pushButton_close_3")
        self.gridLayout_4.addWidget(self.pushButton_close_3, 6, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.select_btn = QtWidgets.QPushButton(self.tab_4)
        self.select_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.select_btn.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.select_btn.setFont(font)
        self.select_btn.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.select_btn.setObjectName("select_btn")
        self.gridLayout_5.addWidget(self.select_btn, 16, 1, 1, 1)
        self.lineEdit_filename_4 = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_filename_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_filename_4.setSizePolicy(sizePolicy)
        self.lineEdit_filename_4.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_filename_4.setMaximumSize(QtCore.QSize(450, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_filename_4.setFont(font)
        self.lineEdit_filename_4.setAutoFillBackground(False)
        self.lineEdit_filename_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_filename_4.setMaxLength(500)
        self.lineEdit_filename_4.setFrame(False)
        self.lineEdit_filename_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_filename_4.setClearButtonEnabled(True)
        self.lineEdit_filename_4.setObjectName("lineEdit_filename_4")
        self.gridLayout_5.addWidget(self.lineEdit_filename_4, 21, 1, 1, 5)
        self.pushButton_export_4 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_export_4.sizePolicy().hasHeightForWidth())
        self.pushButton_export_4.setSizePolicy(sizePolicy)
        self.pushButton_export_4.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_export_4.setFont(font)
        self.pushButton_export_4.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_export_4.setFlat(False)
        self.pushButton_export_4.setObjectName("pushButton_export_4")
        self.gridLayout_5.addWidget(self.pushButton_export_4, 21, 6, 1, 1)
        self.pushButton_close_4 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close_4.sizePolicy().hasHeightForWidth())
        self.pushButton_close_4.setSizePolicy(sizePolicy)
        self.pushButton_close_4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_close_4.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_close_4.setFont(font)
        self.pushButton_close_4.setStyleSheet("QPushButton {\n"
"\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_close_4.setObjectName("pushButton_close_4")
        self.gridLayout_5.addWidget(self.pushButton_close_4, 16, 6, 1, 1)
        self.lineEdit_delay_4 = QtWidgets.QLineEdit(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_delay_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_delay_4.setSizePolicy(sizePolicy)
        self.lineEdit_delay_4.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_delay_4.setFont(font)
        self.lineEdit_delay_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_delay_4.setMaxLength(2)
        self.lineEdit_delay_4.setFrame(False)
        self.lineEdit_delay_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_delay_4.setClearButtonEnabled(True)
        self.lineEdit_delay_4.setObjectName("lineEdit_delay_4")
        self.gridLayout_5.addWidget(self.lineEdit_delay_4, 9, 6, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 6, 0, 1, 2)
        self.connect_message = QtWidgets.QRadioButton(self.tab_4)
        self.connect_message.setEnabled(True)
        self.connect_message.setMinimumSize(QtCore.QSize(250, 30))
        self.connect_message.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.connect_message.setFont(font)
        self.connect_message.setChecked(True)
        self.connect_message.setObjectName("connect_message")
        self.gridLayout_5.addWidget(self.connect_message, 8, 0, 1, 2)
        self.pushButton_start_4 = QtWidgets.QPushButton(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start_4.sizePolicy().hasHeightForWidth())
        self.pushButton_start_4.setSizePolicy(sizePolicy)
        self.pushButton_start_4.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_start_4.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start_4.setFont(font)
        self.pushButton_start_4.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_start_4.setObjectName("pushButton_start_4")
        self.gridLayout_5.addWidget(self.pushButton_start_4, 11, 6, 1, 1)
        self.pause_btn_4 = QtWidgets.QPushButton(self.tab_4)
        self.pause_btn_4.setMinimumSize(QtCore.QSize(0, 0))
        self.pause_btn_4.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pause_btn_4.setFont(font)
        self.pause_btn_4.setStyleSheet("QPushButton {\n"
"    color: #000000;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ffff00, stop: 1 #fed348\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pause_btn_4.setObjectName("pause_btn_4")
        self.gridLayout_5.addWidget(self.pause_btn_4, 13, 6, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 0, 0, 1, 7, QtCore.Qt.AlignHCenter)
        self.spinBox_speed_2 = QtWidgets.QSpinBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_speed_2.sizePolicy().hasHeightForWidth())
        self.spinBox_speed_2.setSizePolicy(sizePolicy)
        self.spinBox_speed_2.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.spinBox_speed_2.setFont(font)
        self.spinBox_speed_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_speed_2.setWrapping(False)
        self.spinBox_speed_2.setFrame(False)
        self.spinBox_speed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_speed_2.setMinimum(-150)
        self.spinBox_speed_2.setMaximum(6000)
        self.spinBox_speed_2.setSingleStep(25)
        self.spinBox_speed_2.setObjectName("spinBox_speed_2")
        self.gridLayout_5.addWidget(self.spinBox_speed_2, 1, 4, 1, 1)
        self.browse_2 = QtWidgets.QPushButton(self.tab_4)
        self.browse_2.setMinimumSize(QtCore.QSize(0, 0))
        self.browse_2.setMaximumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.browse_2.setFont(font)
        self.browse_2.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.browse_2.setObjectName("browse_2")
        self.gridLayout_5.addWidget(self.browse_2, 2, 0, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 3, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(0, 0))
        self.label_17.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 3, 1, 1)
        self.spinBox_try_count_2 = QtWidgets.QSpinBox(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_try_count_2.sizePolicy().hasHeightForWidth())
        self.spinBox_try_count_2.setSizePolicy(sizePolicy)
        self.spinBox_try_count_2.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.spinBox_try_count_2.setFont(font)
        self.spinBox_try_count_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_try_count_2.setFrame(False)
        self.spinBox_try_count_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_try_count_2.setMinimum(2)
        self.spinBox_try_count_2.setMaximum(50)
        self.spinBox_try_count_2.setObjectName("spinBox_try_count_2")
        self.gridLayout_5.addWidget(self.spinBox_try_count_2, 3, 4, 1, 1)
        self.only_message = QtWidgets.QRadioButton(self.tab_4)
        self.only_message.setMinimumSize(QtCore.QSize(199, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.only_message.setFont(font)
        self.only_message.setObjectName("only_message")
        self.gridLayout_5.addWidget(self.only_message, 10, 0, 1, 2)
        self.label_status_4 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status_4.sizePolicy().hasHeightForWidth())
        self.label_status_4.setSizePolicy(sizePolicy)
        self.label_status_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_status_4.setMaximumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_status_4.setFont(font)
        self.label_status_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_4.setObjectName("label_status_4")
        self.gridLayout_5.addWidget(self.label_status_4, 19, 0, 1, 7)
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 21, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.filename_2 = QtWidgets.QLineEdit(self.tab_4)
        self.filename_2.setMinimumSize(QtCore.QSize(480, 38))
        self.filename_2.setMaximumSize(QtCore.QSize(480, 30))
        self.filename_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filename_2.setFrame(False)
        self.filename_2.setObjectName("filename_2")
        self.gridLayout_5.addWidget(self.filename_2, 4, 0, 1, 7)
        self.only_connect = QtWidgets.QRadioButton(self.tab_4)
        self.only_connect.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.only_connect.setFont(font)
        self.only_connect.setObjectName("only_connect")
        self.gridLayout_5.addWidget(self.only_connect, 9, 0, 1, 2)
        self.comboX = QtWidgets.QComboBox(self.tab_4)
        self.comboX.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.comboX.setFont(font)
        self.comboX.setAutoFillBackground(False)
        self.comboX.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboX.setFrame(False)
        self.comboX.setObjectName("comboX")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.gridLayout_5.addWidget(self.comboX, 13, 0, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 16, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 20, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 9, 5, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem1, 15, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 17, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem3, 7, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem5, 14, 1, 1, 1)
        self.lineEdit_page_number_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_page_number_3.setGeometry(QtCore.QRect(382, 382, 1, 1))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_page_number_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_page_number_3.setSizePolicy(sizePolicy)
        self.lineEdit_page_number_3.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_page_number_3.setFont(font)
        self.lineEdit_page_number_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_page_number_3.setMaxLength(3)
        self.lineEdit_page_number_3.setFrame(False)
        self.lineEdit_page_number_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_page_number_3.setClearButtonEnabled(True)
        self.lineEdit_page_number_3.setObjectName("lineEdit_page_number_3")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setMaximumSize(QtCore.QSize(120, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 3, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_5)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_24.setFont(font)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 3, 2, 1, 2, QtCore.Qt.AlignLeft)
        self.label_license_status = QtWidgets.QLabel(self.tab_5)
        self.label_license_status.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_license_status.setFont(font)
        self.label_license_status.setText("")
        self.label_license_status.setObjectName("label_license_status")
        self.gridLayout_6.addWidget(self.label_license_status, 2, 2, 1, 2, QtCore.Qt.AlignLeft)
        self.lineEdit_license_key = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_license_key.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_license_key.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_license_key.setFrame(False)
        self.lineEdit_license_key.setObjectName("lineEdit_license_key")
        self.gridLayout_6.addWidget(self.lineEdit_license_key, 5, 2, 2, 2)
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(13)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 5, 0, 2, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setUnderline(True)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 0, 2, 1, 2, QtCore.Qt.AlignHCenter)
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.textBrowser.setMinimumSize(QtCore.QSize(500, 0))
        self.textBrowser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_6.addWidget(self.textBrowser, 1, 2, 1, 2)
        self.pushButton_delete_old_key = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_delete_old_key.setMaximumSize(QtCore.QSize(220, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        self.pushButton_delete_old_key.setFont(font)
        self.pushButton_delete_old_key.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_delete_old_key.setObjectName("pushButton_delete_old_key")
        self.gridLayout_6.addWidget(self.pushButton_delete_old_key, 8, 3, 1, 1)
        self.pushButton_activate = QtWidgets.QPushButton(self.tab_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_activate.sizePolicy().hasHeightForWidth())
        self.pushButton_activate.setSizePolicy(sizePolicy)
        self.pushButton_activate.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_activate.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_activate.setFont(font)
        self.pushButton_activate.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_activate.setObjectName("pushButton_activate")
        self.gridLayout_6.addWidget(self.pushButton_activate, 8, 2, 1, 1)
        self.tabWidget.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Linkedin Bot "))
        self.people_option.setText(_translate("MainWindow", "Scrape People\'s Profile "))
        self.lineEdit_delay.setText(_translate("MainWindow", "5"))
        self.pause_btn.setText(_translate("MainWindow", "Pause"))
        self.label_3.setText(_translate("MainWindow", "Filename"))
        self.label_7.setText(_translate("MainWindow", "Try Count"))
        self.lineEdit_page_number.setText(_translate("MainWindow", "30"))
        self.label_5.setText(_translate("MainWindow", "Pages Number"))
        self.label_4.setText(_translate("MainWindow", "Delay"))
        self.label_status.setText(_translate("MainWindow", "Remaining: 0 | Profile: 0 | Total Profile: 0"))
        self.pushButton_export.setText(_translate("MainWindow", "Export"))
        self.pushButton_close.setText(_translate("MainWindow", "Close"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.label_6.setText(_translate("MainWindow", "Speed"))
        self.company_option.setText(_translate("MainWindow", "Scrape Company\'s Profile"))
        self.label.setText(_translate("MainWindow", "Linkedin Sales Navigator Scrapper"))
        self.label_26.setText(_translate("MainWindow", "Select one of the Options"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sales Scrapper"))
        self.pushButton_start_2.setText(_translate("MainWindow", "Start"))
        self.label_2.setText(_translate("MainWindow", "Linkedin Sales Navigator People\'s Profile Updater"))
        self.browse.setText(_translate("MainWindow", "add .Xlsx file"))
        self.label_9.setText(_translate("MainWindow", "Filename"))
        self.label_status_2.setText(_translate("MainWindow", "Remaining: 0 | Profile: 0 | Total Profile: 0"))
        self.pushButton_export_2.setText(_translate("MainWindow", "Export"))
        self.lineEdit_delay_2.setText(_translate("MainWindow", "5"))
        self.pushButton_close_2.setText(_translate("MainWindow", "Close"))
        self.pause_btn_2.setText(_translate("MainWindow", "Pause"))
        self.label_8.setText(_translate("MainWindow", "Delay"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sales Updater"))
        self.label_status_3.setText(_translate("MainWindow", "Remaining: 0 | Profile: 0 | Total Profile: 0"))
        self.pushButton_export_3.setText(_translate("MainWindow", "Export"))
        self.label_18.setText(_translate("MainWindow", "Linkedin Job Scraper"))
        self.label_14.setText(_translate("MainWindow", "Delay"))
        self.lineEdit_delay_3.setText(_translate("MainWindow", "5"))
        self.label_13.setText(_translate("MainWindow", "Pages Number"))
        self.lineEdit_page_number_2.setText(_translate("MainWindow", "30"))
        self.label_12.setText(_translate("MainWindow", "Filename"))
        self.pause_btn_3.setText(_translate("MainWindow", "Pause"))
        self.pushButton_start_3.setText(_translate("MainWindow", "Start"))
        self.pushButton_close_3.setText(_translate("MainWindow", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Job Scraper"))
        self.select_btn.setText(_translate("MainWindow", "Select"))
        self.pushButton_export_4.setText(_translate("MainWindow", "Export"))
        self.pushButton_close_4.setText(_translate("MainWindow", "Close"))
        self.lineEdit_delay_4.setText(_translate("MainWindow", "5"))
        self.label_20.setText(_translate("MainWindow", "Select one of the Options"))
        self.connect_message.setText(_translate("MainWindow", "  Send Connect && Message"))
        self.pushButton_start_4.setText(_translate("MainWindow", "Start"))
        self.pause_btn_4.setText(_translate("MainWindow", "Pause"))
        self.label_19.setText(_translate("MainWindow", "Linkedin Connect Message Request Automation"))
        self.browse_2.setText(_translate("MainWindow", "add .Xlsx file"))
        self.label_11.setText(_translate("MainWindow", "Try Count"))
        self.label_17.setText(_translate("MainWindow", "Speed"))
        self.only_message.setText(_translate("MainWindow", " Send Only Message"))
        self.label_status_4.setText(_translate("MainWindow", "Remaining: 0 | Profile: 0 | Total Profile: 0"))
        self.label_10.setText(_translate("MainWindow", "Filename"))
        self.only_connect.setText(_translate("MainWindow", "  Send Only Connect"))
        self.comboX.setItemText(0, _translate("MainWindow", "Select Your Account Type"))
        self.comboX.setItemText(1, _translate("MainWindow", "Sales_Navigator"))
        self.comboX.setItemText(2, _translate("MainWindow", "Normal"))
        self.label_16.setText(_translate("MainWindow", "Pages Number"))
        self.label_15.setText(_translate("MainWindow", "Delay"))
        self.lineEdit_page_number_3.setText(_translate("MainWindow", "30"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Connect && Message"))
        self.label_23.setText(_translate("MainWindow", "Registered To:"))
        self.label_22.setText(_translate("MainWindow", "Your License:"))
        self.label_21.setText(_translate("MainWindow", "License Key:"))
        self.label_25.setText(_translate("MainWindow", "Notice Board"))
        self.pushButton_delete_old_key.setText(_translate("MainWindow", "Delete Old Key"))
        self.pushButton_activate.setText(_translate("MainWindow", "Activate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "About"))
