# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 743)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(160, 50, 302, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_password.sizePolicy().hasHeightForWidth())
        self.lineEdit_password.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_password.setMaxLength(500)
        self.lineEdit_password.setFrame(False)
        self.lineEdit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_password.setClearButtonEnabled(True)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(160, 10, 302, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_email.sizePolicy().hasHeightForWidth())
        self.lineEdit_email.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_email.setFont(font)
        self.lineEdit_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_email.setMaxLength(500)
        self.lineEdit_email.setFrame(False)
        self.lineEdit_email.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_email.setClearButtonEnabled(True)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 72, 33))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 180, 541, 551))
        self.tabWidget.setStyleSheet("background-color:rgb(238, 238, 238);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_export = QtWidgets.QPushButton(self.tab)
        self.pushButton_export.setGeometry(QtCore.QRect(200, 470, 107, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_export.sizePolicy().hasHeightForWidth())
        self.pushButton_export.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_export.setFont(font)
        self.pushButton_export.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_export.setFlat(False)
        self.pushButton_export.setObjectName("pushButton_export")
        self.pushButton_start = QtWidgets.QPushButton(self.tab)
        self.pushButton_start.setGeometry(QtCore.QRect(350, 290, 124, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start.sizePolicy().hasHeightForWidth())
        self.pushButton_start.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_start.setObjectName("pushButton_start")
        self.spinBox_speed = QtWidgets.QSpinBox(self.tab)
        self.spinBox_speed.setGeometry(QtCore.QRect(170, 210, 171, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_speed.sizePolicy().hasHeightForWidth())
        self.spinBox_speed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.spinBox_speed.setFont(font)
        self.spinBox_speed.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_speed.setWrapping(False)
        self.spinBox_speed.setFrame(False)
        self.spinBox_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_speed.setMinimum(-150)
        self.spinBox_speed.setMaximum(6000)
        self.spinBox_speed.setSingleStep(25)
        self.spinBox_speed.setObjectName("spinBox_speed")
        self.lineEdit_filename = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_filename.setGeometry(QtCore.QRect(170, 430, 302, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_filename.sizePolicy().hasHeightForWidth())
        self.lineEdit_filename.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_filename.setFont(font)
        self.lineEdit_filename.setAutoFillBackground(False)
        self.lineEdit_filename.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_filename.setMaxLength(500)
        self.lineEdit_filename.setFrame(False)
        self.lineEdit_filename.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_filename.setClearButtonEnabled(True)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(70, 250, 73, 33))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lineEdit_page_number = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_page_number.setGeometry(QtCore.QRect(172, 330, 171, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_page_number.sizePolicy().hasHeightForWidth())
        self.lineEdit_page_number.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_page_number.setFont(font)
        self.lineEdit_page_number.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_page_number.setMaxLength(3)
        self.lineEdit_page_number.setFrame(False)
        self.lineEdit_page_number.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_page_number.setClearButtonEnabled(True)
        self.lineEdit_page_number.setObjectName("lineEdit_page_number")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(89, 290, 42, 34))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_delay = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_delay.setGeometry(QtCore.QRect(172, 290, 171, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_delay.sizePolicy().hasHeightForWidth())
        self.lineEdit_delay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_delay.setFont(font)
        self.lineEdit_delay.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_delay.setMaxLength(2)
        self.lineEdit_delay.setFrame(False)
        self.lineEdit_delay.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_delay.setClearButtonEnabled(True)
        self.lineEdit_delay.setObjectName("lineEdit_delay")
        self.spinBox_try_count = QtWidgets.QSpinBox(self.tab)
        self.spinBox_try_count.setGeometry(QtCore.QRect(169, 250, 171, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_try_count.sizePolicy().hasHeightForWidth())
        self.spinBox_try_count.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.spinBox_try_count.setFont(font)
        self.spinBox_try_count.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_try_count.setFrame(False)
        self.spinBox_try_count.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_try_count.setMinimum(2)
        self.spinBox_try_count.setMaximum(50)
        self.spinBox_try_count.setObjectName("spinBox_try_count")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(70, 430, 68, 33))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_close = QtWidgets.QPushButton(self.tab)
        self.pushButton_close.setGeometry(QtCore.QRect(350, 330, 124, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close.sizePolicy().hasHeightForWidth())
        self.pushButton_close.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_close.setFont(font)
        self.pushButton_close.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_close.setObjectName("pushButton_close")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(84, 210, 47, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_status = QtWidgets.QLabel(self.tab)
        self.label_status.setGeometry(QtCore.QRect(50, 380, 426, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status.sizePolicy().hasHeightForWidth())
        self.label_status.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(55, 330, 110, 34))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.people_option = QtWidgets.QRadioButton(self.tab)
        self.people_option.setGeometry(QtCore.QRect(30, 130, 221, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.people_option.setFont(font)
        self.people_option.setObjectName("people_option")
        self.company_option = QtWidgets.QRadioButton(self.tab)
        self.company_option.setGeometry(QtCore.QRect(30, 160, 241, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.company_option.setFont(font)
        self.company_option.setObjectName("company_option")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 80, 311, 38))
        self.textBrowser_2.setMinimumSize(QtCore.QSize(240, 38))
        self.textBrowser_2.setMaximumSize(QtCore.QSize(350, 38))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("border:none;\n"
"background-color:rgb(230, 230, 230);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(50, 20, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color:rgb(248, 244, 244);")
        self.textEdit.setObjectName("textEdit")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_start_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_start_2.setGeometry(QtCore.QRect(21, 205, 170, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start_2.sizePolicy().hasHeightForWidth())
        self.pushButton_start_2.setSizePolicy(sizePolicy)
        self.pushButton_start_2.setMinimumSize(QtCore.QSize(170, 40))
        self.pushButton_start_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start_2.setFont(font)
        self.pushButton_start_2.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_start_2.setObjectName("pushButton_start_2")
        self.lineEdit_filename_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_filename_2.setGeometry(QtCore.QRect(110, 440, 254, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_filename_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_filename_2.setSizePolicy(sizePolicy)
        self.lineEdit_filename_2.setMaximumSize(QtCore.QSize(350, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_filename_2.setFont(font)
        self.lineEdit_filename_2.setAutoFillBackground(False)
        self.lineEdit_filename_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_filename_2.setMaxLength(500)
        self.lineEdit_filename_2.setFrame(False)
        self.lineEdit_filename_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_filename_2.setClearButtonEnabled(True)
        self.lineEdit_filename_2.setObjectName("lineEdit_filename_2")
        self.pause_btn = QtWidgets.QPushButton(self.tab_2)
        self.pause_btn.setGeometry(QtCore.QRect(21, 247, 131, 36))
        self.pause_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.pause_btn.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pause_btn.setFont(font)
        self.pause_btn.setStyleSheet("QPushButton {\n"
"    color: #000000;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ffff00, stop: 1 #fed348\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pause_btn.setObjectName("pause_btn")
        self.label_8 = QtWidgets.QLabel(self.tab_2)
        self.label_8.setGeometry(QtCore.QRect(297, 247, 100, 36))
        self.label_8.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(21, 442, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.browse = QtWidgets.QPushButton(self.tab_2)
        self.browse.setGeometry(QtCore.QRect(21, 108, 200, 40))
        self.browse.setMinimumSize(QtCore.QSize(200, 0))
        self.browse.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.browse.setFont(font)
        self.browse.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    ")
        self.browse.setObjectName("browse")
        self.pushButton_close_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_close_2.setGeometry(QtCore.QRect(21, 290, 131, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close_2.sizePolicy().hasHeightForWidth())
        self.pushButton_close_2.setSizePolicy(sizePolicy)
        self.pushButton_close_2.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_close_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_close_2.setFont(font)
        self.pushButton_close_2.setStyleSheet("QPushButton {\n"
"    color: #FF0000;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_close_2.setObjectName("pushButton_close_2")
        self.pushButton_export_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_export_2.setGeometry(QtCore.QRect(390, 440, 107, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_export_2.sizePolicy().hasHeightForWidth())
        self.pushButton_export_2.setSizePolicy(sizePolicy)
        self.pushButton_export_2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_export_2.setFont(font)
        self.pushButton_export_2.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_export_2.setFlat(False)
        self.pushButton_export_2.setObjectName("pushButton_export_2")
        self.filename = QtWidgets.QLineEdit(self.tab_2)
        self.filename.setGeometry(QtCore.QRect(21, 159, 480, 38))
        self.filename.setMinimumSize(QtCore.QSize(480, 38))
        self.filename.setMaximumSize(QtCore.QSize(480, 30))
        self.filename.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filename.setObjectName("filename")
        self.label_status_2 = QtWidgets.QLabel(self.tab_2)
        self.label_status_2.setGeometry(QtCore.QRect(10, 360, 500, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status_2.sizePolicy().hasHeightForWidth())
        self.label_status_2.setSizePolicy(sizePolicy)
        self.label_status_2.setMinimumSize(QtCore.QSize(400, 60))
        self.label_status_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_status_2.setFont(font)
        self.label_status_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_2.setObjectName("label_status_2")
        self.lineEdit_delay_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_delay_2.setGeometry(QtCore.QRect(420, 250, 70, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_delay_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_delay_2.setSizePolicy(sizePolicy)
        self.lineEdit_delay_2.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_delay_2.setFont(font)
        self.lineEdit_delay_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_delay_2.setMaxLength(2)
        self.lineEdit_delay_2.setFrame(False)
        self.lineEdit_delay_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_delay_2.setClearButtonEnabled(True)
        self.lineEdit_delay_2.setObjectName("lineEdit_delay_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_2.setGeometry(QtCore.QRect(0, 20, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color:rgb(248, 244, 244);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton_close_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_close_3.setGeometry(QtCore.QRect(340, 240, 124, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close_3.sizePolicy().hasHeightForWidth())
        self.pushButton_close_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_close_3.setFont(font)
        self.pushButton_close_3.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_close_3.setObjectName("pushButton_close_3")
        self.label_status_3 = QtWidgets.QLabel(self.tab_3)
        self.label_status_3.setGeometry(QtCore.QRect(40, 300, 426, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status_3.sizePolicy().hasHeightForWidth())
        self.label_status_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_status_3.setFont(font)
        self.label_status_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_3.setObjectName("label_status_3")
        self.pushButton_export_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_export_3.setGeometry(QtCore.QRect(200, 420, 107, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_export_3.sizePolicy().hasHeightForWidth())
        self.pushButton_export_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_export_3.setFont(font)
        self.pushButton_export_3.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_export_3.setFlat(False)
        self.pushButton_export_3.setObjectName("pushButton_export_3")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(74, 360, 68, 33))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(45, 240, 110, 34))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(79, 180, 42, 34))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEdit_delay_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_delay_3.setGeometry(QtCore.QRect(162, 180, 171, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_delay_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_delay_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_delay_3.setFont(font)
        self.lineEdit_delay_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_delay_3.setMaxLength(2)
        self.lineEdit_delay_3.setFrame(False)
        self.lineEdit_delay_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_delay_3.setClearButtonEnabled(True)
        self.lineEdit_delay_3.setObjectName("lineEdit_delay_3")
        self.lineEdit_page_number_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_page_number_2.setGeometry(QtCore.QRect(162, 240, 171, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_page_number_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_page_number_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_page_number_2.setFont(font)
        self.lineEdit_page_number_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_page_number_2.setMaxLength(3)
        self.lineEdit_page_number_2.setFrame(False)
        self.lineEdit_page_number_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_page_number_2.setClearButtonEnabled(True)
        self.lineEdit_page_number_2.setObjectName("lineEdit_page_number_2")
        self.pushButton_start_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_start_3.setGeometry(QtCore.QRect(340, 180, 124, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start_3.sizePolicy().hasHeightForWidth())
        self.pushButton_start_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start_3.setFont(font)
        self.pushButton_start_3.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_start_3.setObjectName("pushButton_start_3")
        self.lineEdit_filename_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_filename_3.setGeometry(QtCore.QRect(170, 360, 302, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_filename_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_filename_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_filename_3.setFont(font)
        self.lineEdit_filename_3.setAutoFillBackground(False)
        self.lineEdit_filename_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_filename_3.setMaxLength(500)
        self.lineEdit_filename_3.setFrame(False)
        self.lineEdit_filename_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_filename_3.setClearButtonEnabled(True)
        self.lineEdit_filename_3.setObjectName("lineEdit_filename_3")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_3.setGeometry(QtCore.QRect(50, 30, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("background-color:rgb(248, 244, 244);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.lineEdit_delay_4 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_delay_4.setGeometry(QtCore.QRect(420, 220, 70, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_delay_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_delay_4.setSizePolicy(sizePolicy)
        self.lineEdit_delay_4.setMaximumSize(QtCore.QSize(70, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_delay_4.setFont(font)
        self.lineEdit_delay_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_delay_4.setMaxLength(2)
        self.lineEdit_delay_4.setFrame(False)
        self.lineEdit_delay_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_delay_4.setClearButtonEnabled(True)
        self.lineEdit_delay_4.setObjectName("lineEdit_delay_4")
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setGeometry(QtCore.QRect(40, 480, 71, 34))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(374, 128, 1, 1))
        self.label_11.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.only_connect = QtWidgets.QRadioButton(self.tab_4)
        self.only_connect.setGeometry(QtCore.QRect(26, 257, 211, 30))
        self.only_connect.setMinimumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.only_connect.setFont(font)
        self.only_connect.setObjectName("only_connect")
        self.lineEdit_filename_4 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_filename_4.setGeometry(QtCore.QRect(130, 480, 241, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_filename_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_filename_4.setSizePolicy(sizePolicy)
        self.lineEdit_filename_4.setMaximumSize(QtCore.QSize(350, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_filename_4.setFont(font)
        self.lineEdit_filename_4.setAutoFillBackground(False)
        self.lineEdit_filename_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_filename_4.setMaxLength(500)
        self.lineEdit_filename_4.setFrame(False)
        self.lineEdit_filename_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_filename_4.setClearButtonEnabled(True)
        self.lineEdit_filename_4.setObjectName("lineEdit_filename_4")
        self.connect_message = QtWidgets.QRadioButton(self.tab_4)
        self.connect_message.setEnabled(True)
        self.connect_message.setGeometry(QtCore.QRect(26, 222, 271, 30))
        self.connect_message.setMinimumSize(QtCore.QSize(250, 30))
        self.connect_message.setMaximumSize(QtCore.QSize(300, 25))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.connect_message.setFont(font)
        self.connect_message.setObjectName("connect_message")
        self.pushButton_close_4 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_close_4.setGeometry(QtCore.QRect(380, 390, 120, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_close_4.sizePolicy().hasHeightForWidth())
        self.pushButton_close_4.setSizePolicy(sizePolicy)
        self.pushButton_close_4.setMinimumSize(QtCore.QSize(120, 30))
        self.pushButton_close_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_close_4.setFont(font)
        self.pushButton_close_4.setStyleSheet("QPushButton {\n"
"    color: #FF0000;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_close_4.setObjectName("pushButton_close_4")
        self.browse_2 = QtWidgets.QPushButton(self.tab_4)
        self.browse_2.setGeometry(QtCore.QRect(26, 83, 181, 40))
        self.browse_2.setMinimumSize(QtCore.QSize(100, 0))
        self.browse_2.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.browse_2.setFont(font)
        self.browse_2.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    ")
        self.browse_2.setObjectName("browse_2")
        self.label_15 = QtWidgets.QLabel(self.tab_4)
        self.label_15.setGeometry(QtCore.QRect(310, 220, 109, 30))
        self.label_15.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.pushButton_start_4 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_start_4.setGeometry(QtCore.QRect(330, 300, 170, 40))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_start_4.sizePolicy().hasHeightForWidth())
        self.pushButton_start_4.setSizePolicy(sizePolicy)
        self.pushButton_start_4.setMinimumSize(QtCore.QSize(170, 40))
        self.pushButton_start_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_start_4.setFont(font)
        self.pushButton_start_4.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_start_4.setObjectName("pushButton_start_4")
        self.pause_btn_2 = QtWidgets.QPushButton(self.tab_4)
        self.pause_btn_2.setGeometry(QtCore.QRect(380, 350, 120, 36))
        self.pause_btn_2.setMinimumSize(QtCore.QSize(120, 0))
        self.pause_btn_2.setMaximumSize(QtCore.QSize(16777215, 36))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pause_btn_2.setFont(font)
        self.pause_btn_2.setStyleSheet("QPushButton {\n"
"    color: #000000;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #ffff00, stop: 1 #fed348\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pause_btn_2.setObjectName("pause_btn_2")
        self.filename_2 = QtWidgets.QLineEdit(self.tab_4)
        self.filename_2.setGeometry(QtCore.QRect(26, 134, 480, 38))
        self.filename_2.setMinimumSize(QtCore.QSize(480, 38))
        self.filename_2.setMaximumSize(QtCore.QSize(480, 30))
        self.filename_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.filename_2.setObjectName("filename_2")
        self.comboX = QtWidgets.QComboBox(self.tab_4)
        self.comboX.setGeometry(QtCore.QRect(10, 340, 281, 40))
        self.comboX.setMinimumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboX.setFont(font)
        self.comboX.setAutoFillBackground(False)
        self.comboX.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboX.setObjectName("comboX")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.comboX.addItem("")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser.setGeometry(QtCore.QRect(10, 180, 311, 38))
        self.textBrowser.setMinimumSize(QtCore.QSize(240, 38))
        self.textBrowser.setMaximumSize(QtCore.QSize(350, 38))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("border:none;\n"
"background-color:rgb(230, 230, 230);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(374, 382, 1, 1))
        self.label_16.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_page_number_3 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_page_number_3.setGeometry(QtCore.QRect(382, 382, 1, 1))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_page_number_3.sizePolicy().hasHeightForWidth())
        self.lineEdit_page_number_3.setSizePolicy(sizePolicy)
        self.lineEdit_page_number_3.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.lineEdit_page_number_3.setFont(font)
        self.lineEdit_page_number_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_page_number_3.setMaxLength(3)
        self.lineEdit_page_number_3.setFrame(False)
        self.lineEdit_page_number_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_page_number_3.setClearButtonEnabled(True)
        self.lineEdit_page_number_3.setObjectName("lineEdit_page_number_3")
        self.label_17 = QtWidgets.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(374, 82, 1, 1))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMinimumSize(QtCore.QSize(0, 0))
        self.label_17.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.spinBox_speed_2 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_speed_2.setGeometry(QtCore.QRect(382, 82, 1, 1))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_speed_2.sizePolicy().hasHeightForWidth())
        self.spinBox_speed_2.setSizePolicy(sizePolicy)
        self.spinBox_speed_2.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.spinBox_speed_2.setFont(font)
        self.spinBox_speed_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_speed_2.setWrapping(False)
        self.spinBox_speed_2.setFrame(False)
        self.spinBox_speed_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_speed_2.setMinimum(-150)
        self.spinBox_speed_2.setMaximum(6000)
        self.spinBox_speed_2.setSingleStep(25)
        self.spinBox_speed_2.setObjectName("spinBox_speed_2")
        self.only_message = QtWidgets.QRadioButton(self.tab_4)
        self.only_message.setGeometry(QtCore.QRect(30, 290, 221, 32))
        self.only_message.setMinimumSize(QtCore.QSize(199, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.only_message.setFont(font)
        self.only_message.setObjectName("only_message")
        self.label_status_4 = QtWidgets.QLabel(self.tab_4)
        self.label_status_4.setGeometry(QtCore.QRect(20, 420, 500, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_status_4.sizePolicy().hasHeightForWidth())
        self.label_status_4.setSizePolicy(sizePolicy)
        self.label_status_4.setMinimumSize(QtCore.QSize(500, 60))
        self.label_status_4.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_status_4.setFont(font)
        self.label_status_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status_4.setObjectName("label_status_4")
        self.spinBox_try_count_2 = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_try_count_2.setGeometry(QtCore.QRect(382, 128, 1, 1))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_try_count_2.sizePolicy().hasHeightForWidth())
        self.spinBox_try_count_2.setSizePolicy(sizePolicy)
        self.spinBox_try_count_2.setMaximumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.spinBox_try_count_2.setFont(font)
        self.spinBox_try_count_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinBox_try_count_2.setFrame(False)
        self.spinBox_try_count_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_try_count_2.setMinimum(2)
        self.spinBox_try_count_2.setMaximum(50)
        self.spinBox_try_count_2.setObjectName("spinBox_try_count_2")
        self.select_btn = QtWidgets.QPushButton(self.tab_4)
        self.select_btn.setGeometry(QtCore.QRect(26, 388, 200, 30))
        self.select_btn.setMinimumSize(QtCore.QSize(200, 30))
        self.select_btn.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.select_btn.setObjectName("select_btn")
        self.pushButton_export_4 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_export_4.setGeometry(QtCore.QRect(390, 480, 107, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_export_4.sizePolicy().hasHeightForWidth())
        self.pushButton_export_4.setSizePolicy(sizePolicy)
        self.pushButton_export_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_export_4.setFont(font)
        self.pushButton_export_4.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_export_4.setFlat(False)
        self.pushButton_export_4.setObjectName("pushButton_export_4")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_4)
        self.textEdit_4.setGeometry(QtCore.QRect(0, 10, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("background-color:rgb(248, 244, 244);")
        self.textEdit_4.setObjectName("textEdit_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_5.setGeometry(QtCore.QRect(110, 20, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit_5.setFont(font)
        self.textEdit_5.setStyleSheet("background-color:rgb(248, 244, 244);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.checkBox_remember_me = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_remember_me.setGeometry(QtCore.QRect(190, 80, 171, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_remember_me.sizePolicy().hasHeightForWidth())
        self.checkBox_remember_me.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.checkBox_remember_me.setFont(font)
        self.checkBox_remember_me.setChecked(False)
        self.checkBox_remember_me.setObjectName("checkBox_remember_me")
        self.pushButton_login = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_login.setGeometry(QtCore.QRect(210, 130, 99, 34))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_login.sizePolicy().hasHeightForWidth())
        self.pushButton_login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_login.setFont(font)
        self.pushButton_login.setStyleSheet("QPushButton {\n"
"    color: #1E1E1E;\n"
"    border: 1px solid #555;\n"
"    border-radius: 3px;\n"
"    border-style: Solid;\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #e5e5e5, stop: 1 #79d70f\n"
"        );\n"
"    padding: 5px 28px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"\n"
"QPushButton:pressed {\n"
"    border-style: inset;\n"
"    background: qradialgradient(\n"
"        cx: 0.4, cy: -0.1, fx: 0.4, fy: -0.1,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #ddd\n"
"        );\n"
"    }")
        self.pushButton_login.setObjectName("pushButton_login")
        self.lineEdit_password.raise_()
        self.label.raise_()
        self.lineEdit_email.raise_()
        self.label_2.raise_()
        self.checkBox_remember_me.raise_()
        self.tabWidget.raise_()
        self.pushButton_login.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Linkedin Bot "))
        self.label.setText(_translate("MainWindow", "Email"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.pushButton_export.setText(_translate("MainWindow", "Export"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.label_7.setText(_translate("MainWindow", "Try Count"))
        self.lineEdit_page_number.setText(_translate("MainWindow", "30"))
        self.label_4.setText(_translate("MainWindow", "Delay"))
        self.lineEdit_delay.setText(_translate("MainWindow", "5"))
        self.label_3.setText(_translate("MainWindow", "Filename"))
        self.pushButton_close.setText(_translate("MainWindow", "Close"))
        self.label_6.setText(_translate("MainWindow", "Speed"))
        self.label_status.setText(_translate("MainWindow", "Remaining: 0 | Profile: 0 | Total Profile: 0"))
        self.label_5.setText(_translate("MainWindow", "Pages Number"))
        self.people_option.setText(_translate("MainWindow", "Scrape People\'s Profile "))
        self.company_option.setText(_translate("MainWindow", "Scrape Company\'s Profile"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Select one of the Options</span></p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Linkedin Sales Navigator Scrapper</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sales Scrapper"))
        self.pushButton_start_2.setText(_translate("MainWindow", "Start"))
        self.pause_btn.setText(_translate("MainWindow", "Pause"))
        self.label_8.setText(_translate("MainWindow", "         Delay"))
        self.label_9.setText(_translate("MainWindow", "Filename"))
        self.browse.setText(_translate("MainWindow", "add .Xlsx file"))
        self.pushButton_close_2.setText(_translate("MainWindow", "Close"))
        self.pushButton_export_2.setText(_translate("MainWindow", "Export"))
        self.label_status_2.setText(_translate("MainWindow", "Remaining: 0 | Profile: 0 | Total Profile: 0"))
        self.lineEdit_delay_2.setText(_translate("MainWindow", "5"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Linkedin Sales Navigator People\'s Profile Updater</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sales Updater"))
        self.pushButton_close_3.setText(_translate("MainWindow", "Close"))
        self.label_status_3.setText(_translate("MainWindow", "Remaining: 0 | Profile: 0 | Total Profile: 0"))
        self.pushButton_export_3.setText(_translate("MainWindow", "Export"))
        self.label_12.setText(_translate("MainWindow", "Filename"))
        self.label_13.setText(_translate("MainWindow", "Pages Number"))
        self.label_14.setText(_translate("MainWindow", "Delay"))
        self.lineEdit_delay_3.setText(_translate("MainWindow", "5"))
        self.lineEdit_page_number_2.setText(_translate("MainWindow", "30"))
        self.pushButton_start_3.setText(_translate("MainWindow", "Start"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Linkedin Job Scraper</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Job Scraper"))
        self.lineEdit_delay_4.setText(_translate("MainWindow", "5"))
        self.label_10.setText(_translate("MainWindow", "Filename"))
        self.label_11.setText(_translate("MainWindow", "Try Count"))
        self.only_connect.setText(_translate("MainWindow", "  Send Only Connect"))
        self.connect_message.setText(_translate("MainWindow", "  Send Connect && Message"))
        self.pushButton_close_4.setText(_translate("MainWindow", "Close"))
        self.browse_2.setText(_translate("MainWindow", "add .Xlsx file"))
        self.label_15.setText(_translate("MainWindow", "         Delay"))
        self.pushButton_start_4.setText(_translate("MainWindow", "Start"))
        self.pause_btn_2.setText(_translate("MainWindow", "Pause"))
        self.comboX.setItemText(0, _translate("MainWindow", "Select Your Account Type"))
        self.comboX.setItemText(1, _translate("MainWindow", "Sales_Navigator"))
        self.comboX.setItemText(2, _translate("MainWindow", "Normal"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:16pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt;\">Select one of the Options</span></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "Pages Number"))
        self.lineEdit_page_number_3.setText(_translate("MainWindow", "30"))
        self.label_17.setText(_translate("MainWindow", "Speed"))
        self.only_message.setText(_translate("MainWindow", " Send Only Message"))
        self.label_status_4.setText(_translate("MainWindow", "Remaining: 0 | Profile: 0 | Total Profile: 0"))
        self.select_btn.setText(_translate("MainWindow", "Select"))
        self.pushButton_export_4.setText(_translate("MainWindow", "Export"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Linkedin Connect &amp; Message Request Automation</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Connect && Message"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">REGISTRATION</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Registration"))
        self.checkBox_remember_me.setText(_translate("MainWindow", "Remember me"))
        self.pushButton_login.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
